#spring.application.name=JournalApplication
##spring.data.mongodb.host=localhost
##print.data.mongodb.port=27017
#spring.data.mongodb.database=journaldb
#sprint.data.mongodb.auto-index-creation=true
##spring.data.mongodb.username=journaldb
##spring.data.mongodb.password=journaldb
#spring.data.mongodb.uri=mongodb+srv://saqlainzarjisansari:KSg8arf7VKCWhzGg@cluster0.08nfq9f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#server.port=9091
#
## we can also create application.yml easy jazzy things rather this of writing same sping. again and again, works on indentation
##server.servlet.context-path=/app

spring:
  profiles:
    active: dev

weather:
  api:
    key: 049bd019f87458fd72f954754ce40ef0

